### ISSUE TITLE
Add a Travis job that runs 'terraform validate'

### ISSUE THREAD

**Issue by edmorley** [mozilla-platform-ops/devservices-aws#54]
Terraform has a command that checks for syntax errors:
https://www.terraform.io/docs/commands/validate.html

It would be good to run this on Travis, like done here:
https://github.com/travis-infrastructure/terraform-config/blob/master/.travis.yml
https://github.com/travis-infrastructure/terraform-config/blob/7ed91676a42e17e2e6d03ecaa699c3f615acd4bd/runtests#L43

**Comment by klibby** [comment]
Now I just need github support to unflag @devsvcs-travis, the account I set up to connect this repo to travis...
