### ISSUE TITLE
Enable github-bugzilla-pr-linker on this repo

### ISSUE THREAD

**Issue by edmorley** [mozilla-platform-ops/devservices-aws#78]
Please can the [github-bugzilla-pr-linker](https://github.com/mozilla/github-bugzilla-pr-linker) be enabled on this repo?

Steps here:
https://mana.mozilla.org/wiki/display/WebDev/GitHub+Bugzilla+PR+Linker

Many thanks :-)

**Comment by klibby** [comment]
Added!

**Comment by edmorley** [comment]
Many thanks :-)
